// Generated by https://quicktype.io

export interface PlacesResponse {
  type:      string;
  geocoding: PlacesResponseGeocoding;
  features:  Feature[];
}

export interface Feature {
  type:       FeatureType;
  properties: Properties;
  geometry:   Geometry;
}

export interface Geometry {
  type:        GeometryType;
  coordinates: number[];
}

export enum GeometryType {
  Point = "Point",
}

export interface Properties {
  geocoding: PropertiesGeocoding;
}

export interface PropertiesGeocoding {
  place_id:  number;
  osm_type:  OsmType;
  osm_id:    number;
  osm_key:   OsmKey;
  osm_value: OsmValue;
  type:      GeocodingType;
  label:     string;
  name:      Name;
}

export enum Name {
  ElRetiro = "El Retiro",
}

export enum OsmKey {
  Boundary = "boundary",
  Place = "place",
}

export enum OsmType {
  Node = "node",
  Relation = "relation",
  Way = "way",
}

export enum OsmValue {
  Administrative = "administrative",
  Suburb = "suburb",
  Village = "village",
}

export enum GeocodingType {
  City = "city",
  District = "district",
  Locality = "locality",
}

export enum FeatureType {
  Feature = "Feature",
}

export interface PlacesResponseGeocoding {
  version:     string;
  attribution: string;
  licence:     string;
  query:       string;
}
